image: docker:latest
services:
- docker:dind

stages:
- release

variables:
  DOCKER_DRIVER: overlay2
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

release:
  stage: release
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
  only:
    - develop